### ISSUE TITLE
10-min tutorial ATN dependency issues

### ISSUE THREAD

**Issue by mlkimmins** [fugue-project/tutorials#167]
Hello~ New user here.

I am following the 10-min Fugue SQL tutorial, I'm encountering ATN dependency issues

Could not deserialize ATN with version  (expected 4)

This is after I have made sure I have pip installed 

pip install antlr4-python3-runtime==4.11.0

Runtime env is conda venv on Jupyterlab. I'm thinking it may be a version mismatch, ATN seems to require a specific version in which the lexer / parser was compiled in. Can you share what the exact antlr runtime I should have? And surface that in the documentation?

**Comment by kvnkho** [comment]
Hey @mlkimmins,

First off the quick answer is that you need `antlr4-python3-runtime==4.11.1` because it had breaking changes. We mentioned this in the Slack thread. 

Writing here to mention we couldn't replicate after trying the following:

1. Pip installing Fugue in fresh conda Python 3.8 environment
2. Conda installing Fugue in fresh conda Python 3.8 environment
3. Installing antlr4-python3-runtime==4.11.0 and then installing Fugue (it upgrades to the right version we have pinned).

Are you still blocked by this after installing `antlr4-python3-runtime==4.11.1`? Do you have more details that might help me replicate this?

Totally understand the suggestion to include it in docs, though ideally, users shouldn't have to worry about this.

**Comment by mlkimmins** [comment]
Got it~ 

With antlr == 4.11.1, it was resolved.

Here's a snippet of my yml file for conda environemnt that solved it:


channels:
- conda-forge

dependencies:
- jupyterlab
- matplotlib
- numpy
- pandas
- papermill
- pillow
- pip
- python>=3.9
- requests
- retrolab
- scipy
- scikit-learn
- seaborn
- statsmodels
- voila
- dask
- dask-yarn
# - dask.distributed
- distributed
- tensorflow
# - skorch
# - torchvision
- s3fs
- pyarrow
- cloudpickle
- lz4
- xgboost
- antlr4-python3-runtime==4.11.1
- fugue
