### ISSUE TITLE
Explain schema in beginner/interface.ipynb

### ISSUE THREAD

**Issue by rdmolony** [fugue-project/tutorials#71]
Hi there,

> # Schema

> This leads us to schema.  Schema is explicit in Fugue for a couple of reasons. First, is to allow quick validation if the computation job contains all the necessary columns. 

> Beyond this, explicit schema is very important in a distributed setting. The DataFrame can be split across multiple machines, and each machine only sees the data it holds. A strong schema guarantees that operations are performed as expected across all machines. A lot of heavy pandas users are not used to explicit schema but it becomes more important in a distributed setting. Inferring schema is an expensive operation. There are 3 basic ways to define schema with Fugue. Note that we are specifying the output schema of the extension.

This might be made a little clearer, but I'm not quite sure how:

- [x] What is schema?
- [x] How does it guarantee operations perform as expected?

**Comment by kvnkho** [comment]
This is a good suggestion. I just think `strong schema` should be `explicit schema` in number 2. 

You are exactly right with number 1, Fugue can error out quickly because of the DAG it creates if there is a schema mismatch.

[This ](https://fugue-tutorials.readthedocs.io/en/latest/tutorials/extensions/index.html#output-schema-requirement)also has some information about number 3 that you can incorporate. 

It is also important to note that schema is a requirement for using Spark and Dask in general and using user-defined functions. Fugue as an abstraction layer on provides a simpler interface to work with these.

**Comment by rdmolony** [comment]
Thanks Kevin, how about:

3. Inferring schema is an expensive and error-prone operation.  To infer the schema, distributed computing frameworks have to go through at least one partition of data to figure out the possible schema.  If the inferred schema is inconsistent across partitions, the result will be wrong.

**Comment by kvnkho** [comment]
Yeah that sounds right!

**Comment by rdmolony** [comment]
Great, thanks Kevin, I'll add the above into the beginner/ docs once #79 has either merged or closed!
